language: ruby
cache: bundler
sudo: false
rvm:
- 2.3
- 2.4
- 2.5
- 2.6
env:
- TASK=test
matrix:
  include:
  - rvm: 2.3 # keep same as lowest ruby version
    env: TASK=rubocop
script: bundle exec rake $TASK
branches:
  only: master
before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'
